
//Authentication Actions
export const SIGN_OUT_USER = 'SIGN_OUT_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';

//Course actions
export const ADD_COURSE = "ADD_COURSE";
export const CREATE_COURSE = "CREATE_COURSE";
export const LEAVE_COURSE = "LEAVE_COURSE";

export const FETCH_ALL_COURSES_REQUEST = "FETCH_ALL_COURSES_REQUEST";
export const FETCH_ALL_COURSES_FAILURE = "FETCH_ALL_COURSES_FAILURE";
export const FETCH_ALL_COURSES_SUCCESS = "FETCH_ALL_COURSES_SUCCESS";

export const FETCH_COURSE = "FETCH_COURSE";
export const FETCH_COURSE_SUCCESS = "FETCH_COURSE_SUCCESS";
