
//Authentication Actions
export const SIGN_OUT_USER = 'SIGN_OUT_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';

//Course actions
export const ADD_COURSE = "ADD_COURSE";
export const CREATE_COURSE = "CREATE_COURSE";
export const LEAVE_COURSE = "LEAVE_COURSE";
export const SELECT_COURSE = "SELECT_COURSE";

export const FETCH_ALL_COURSES_REQUEST = "FETCH_ALL_COURSES_REQUEST";
export const FETCH_ALL_COURSES_FAILURE = "FETCH_ALL_COURSES_FAILURE";
export const FETCH_ALL_COURSES_SUCCESS = "FETCH_ALL_COURSES_SUCCESS";

export const FETCH_COURSE = "FETCH_COURSE";
export const FETCH_COURSE_SUCCESS = "FETCH_COURSE_SUCCESS";

//Assignment Actions
export const CREATE_ASSIGNMENT = "ADD_ASSIGNMENT";
export const DELETE_ASSIGNMENT = "DELETE_ASSIGMENT";

export const FETCH_ASSIGNMENTS_REQUEST = "FETCH_ASSIGNMENTS_REQUEST";
export const FETCH_ASSIGNMENTS_FAILURE = "FETCH_ASSIGNMENTS_FAILURE";
export const FETCH_ASSIGNMENTS_SUCCESS = "FETCH_ASSIGNMENTS_SUCCESS";

export const FETCH_ASSIGNMENT_DETAIL = "FETCH_ASSIGNMENT_DETAIL";
export const FETCH_ASSIGNMENT_DETAIL_SUCCESS = "FETCH_ASSIGNMENT_DETAIL_SUCCESS";
